server:
  port: 3000

spring:
  application:
    name: turbine-aggregator

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

turbine:
  app-config: weather-app,time-app
  cluster-name-expression: "'default'"