
server:
  port: 8001

spring:
  application:
    name: time-app

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"